# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class UserWin(QtWidgets.QWidget):
    def __init__(self,username, model = None, par = None):
        super().__init__(par)
        print(username)
        print(model)
        self.ui = USERUSER()
        self.ui.setupUi(self)
        if username == 'Вы не прошли провеку!':
            self.ui.label_2.setText('Вы никто')
        else:
            text = model.GetAllUsers().to_numpy() 
            for i in text:
                if i[0] == username:
                    text = i[2].replace('\t', ' ')
                    break
            print(text)
            self.ui.label_2.setText(text)

        self.setWindowTitle("Пользователь")


class USERUSER(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 294)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Добро пожаловать:"))
        self.label_2.setText(_translate("Form", "Добро пожаловать:"))
